/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("java")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")
    implementation("com.google.guava:guava:30.1.1-jre")



    // gson
    implementation("com.google.code.gson:gson:2.9.0")

    // mysql
    implementation("com.mysql:mysql-connector-j:8.0.31")

    // javacord
    implementation("org.javacord:javacord:3.5.0")

    // log4j
    runtimeOnly ("org.apache.logging.log4j:log4j-core:2.17.0")
    
}

application {
    // Define the main class for the application.
    mainClass.set("discordbot.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<Jar> {
    manifest.attributes["Main-class"] = "discordbot.App"
}